server:
  # 服务http端口
  port: 8080
  # tomcat配置
  tomcat:
    # 最大线程数
    max-threads: 500
    # 最小线程数
    min-spare-threads: 10

spring:
  profiles:
    active: dev
  application:
    name: learn


logging:
  level: debug
  file: classpath*:config/logback-spring.xml




